apiVersion: v1
kind: Service
metadata:
  name: hello-openshift-custom
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-openshift-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift-custom
  template:
    metadata:
      labels:
        app: hello-openshift-custom
    spec:
      containers:
      - name: hello-openshift
        image: akilada/hello-openshift:0.1
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I just deployed this on Openshift!
